# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysql:
    type: mysql
    size: S
    disk: 1024

redis:
    type: redis
    size: S

solra:
    type: solr
    disk: 512

solrb:
    type: solr
    disk: 512
